# Generated by Django 2.2.5 on 2019-10-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100, null=True, verbose_name='Local')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de termino')),
                ('schedule', models.CharField(max_length=10, verbose_name='Horário')),
                ('frequency', models.CharField(blank=True, choices=[('diário', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('único', 'Único')], default='adoção', max_length=30, null=True, verbose_name='Frequência')),
                ('type_event', models.CharField(blank=True, choices=[('adoção', 'Adoção')], default='adoção', max_length=30, null=True, verbose_name='Tipo de evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Address')),
            ],
            options={
                'permissions': (('access_adoption_event', 'Acessar Eventos de adoção'),),
            },
        ),
    ]
