# Generated by Django 2.2.5 on 2019-10-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('DN', 'Dinheiro'), ('DC', 'Depósito em Conta'), ('TR', 'Transferência')], max_length=30),
        ),
    ]
