# Generated by Django 2.2.5 on 2019-10-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20191001_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('DN', 'Dinheiro'), ('DC', 'Depósito em Conta'), ('TR', 'Transferência'), ('OT', 'Outros')], max_length=30),
        ),
    ]
