# Generated by Django 2.2.5 on 2019-09-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_system', 'Acessar Sistema'), ('admin_user', 'Administrar Usuários'), ('disable_user', 'Desabilitar Usuário')), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
