# Generated by Django 2.2.5 on 2019-09-30 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190929_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
