# Generated by Django 2.2.5 on 2019-09-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190929_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='author',
        ),
    ]
