# Generated by Django 2.2.5 on 2019-10-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('CT', 'Conta de Telefone'), ('CL', 'Conta de Luz'), ('CA', 'Conta de Água'), ('TX', 'Taxi'), ('VT', 'Veterinário'), ('RM', 'Remédios')], max_length=30),
        ),
    ]
