# Generated by Django 2.2.5 on 2019-10-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20191001_1519'),
        ('finance', '0006_auto_20191001_1914'),
    ]

    operations = [
    ]
