# Generated by Django 2.2.5 on 2019-09-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('sex', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], default='F', max_length=1, verbose_name='Sexo')),
                ('birthday', models.DateField(default='AAAA-MM-DD', verbose_name='Data de Nascimento')),
                ('observation', models.CharField(blank=True, max_length=140, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Estado Clínico')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Espécie')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Temporário', 'Temporário'), ('Adoção', 'Adoção')], max_length=10, verbose_name='Categoria')),
                ('entry_date', models.DateField(default='AAAA-MM-DD', verbose_name='Data de Entrada')),
                ('exit_date', models.DateField(blank=True, default='AAAA-MM-DD', null=True, verbose_name='Data de Saída')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name='Animal')),
            ],
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='AAAA-MM-DD', verbose_name='Data')),
                ('observation', models.CharField(blank=True, max_length=140, null=True, verbose_name='Observação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name='Animal')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Health', verbose_name='Estado Clínico')),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Raça')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Species', verbose_name='Espécie')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.Breed', verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.Species', verbose_name='Espécie'),
        ),
    ]
