# Generated by Django 2.2.5 on 2019-09-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthlog',
            name='health',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
    ]
