# Generated by Django 2.2.5 on 2019-10-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_auto_20191001_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='category',
            field=models.CharField(choices=[('temp', 'Temporário'), ('adoção', 'Adoção')], max_length=10, verbose_name='Categoria'),
        ),
    ]
